<?php
session_start();
// Include the database connection file
include('db.php');

// Check if the form is submitted
if (isset($_POST['submit'])) {
    // Get form data
    $name = $_POST['name'];
    $email = $_POST['email'];
    $password = $_POST['password'];
    $confirmPassword = $_POST['confirmPassword'];
    $role = $_POST['role'];

    // Validate if passwords match
    if ($password === $confirmPassword) {
        // Hash the password before storing
        $hashedPassword = password_hash($password, PASSWORD_DEFAULT);

        // Validate email uniqueness
        $stmt = $conn->prepare("SELECT id FROM users WHERE email = ?");
        $stmt->bind_param("s", $email);
        $stmt->execute();
        $stmt->store_result();

        if ($stmt->num_rows > 0) {
            $error_message = "Email already registered!";
        } else {
            // Check if terms are accepted
            if (!isset($_POST['terms'])) {
                $error_message = "You must agree to the terms and conditions!";
            } else {
                $created_at = $updated_at = date("Y-m-d H:i:s");

                // Insert into users table
                $insert_stmt = $conn->prepare("INSERT INTO users (name, email, password, role, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)");
                $insert_stmt->bind_param("ssssss", $name, $email, $hashedPassword, $role, $created_at, $updated_at);

                if ($insert_stmt->execute()) {
                    $user_id = $insert_stmt->insert_id;

                    // After inserting the company into the database
if ($role === 'companies') {
    $company_name = $name . "'s Company";
    $insert_company = $conn->prepare("INSERT INTO companies (user_id, company_name, company_email, company_address, company_phone, company_website) VALUES (?, ?, ?, '', '', '')");
    $insert_company->bind_param("iss", $user_id, $company_name, $email);
    $insert_company->execute();
    
    // Get the company ID (auto-generated by the database)
    $company_id = $insert_company->insert_id;

    // Set the session variables for company
    $_SESSION['company_id'] = $company_id; // Store the company ID in the session
    
    $insert_company->close();
}

// Redirect based on user role
if ($role === 'companies') {
    header('Location: companies.php');  // Redirect to companies page
} else {
    header('Location: gallery.php');  // Redirect to gallery page for customers
}
exit();


                } else {
                    $error_message = "Error while inserting user!";
                }

                $insert_stmt->close();
            }
        }

        $stmt->close();
    } else {
        $error_message = "Passwords do not match!";
    }
}
?>

<!-- HTML Form -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="signup.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/remixicon/fonts/remixicon.css">
    <title>Sign Up</title>
</head>
<body>

<div class="nav">
    <h2 class="logo">
        <i class="fas fa-brain"></i>
        <i class="fas fa-couch"></i>
        RoomGenius
    </h2>
</div>

<div class="background">
    <div class="wrapper">
        <form action="signup.php" method="post">
            <h2>Sign Up</h2>
            <?php
            if (isset($error_message)) {
                echo '<p style="color:red; text-align:center;">' . $error_message . '</p>';
            }
            ?>
            <div class="input-field">
                <div class="input-box">
                    <span class="icon"><i class='bx bxs-user'></i></span>
                    <input type="text" name="name" required>
                    <label>Name</label>
                </div>
                <div class="input-box">
                    <span class="icon"><i class="ri-mail-line"></i></span>
                    <input type="email" name="email" required>
                    <label>Email</label>
                </div>

                <div class="input-box">
                    <span class="icon"><i class='bx bxs-lock-alt'></i></span>
                    <input type="password" id="password" name="password" required oninput="checkPasswordStrength(this.value)">
                    <label>Password</label>
                    <div id="password-strength" class="strength-text"></div>
                </div>

                <div class="input-box">
                    <span class="icon"><i class='bx bxs-lock-alt'></i></span>
                    <input type="password" name="confirmPassword" required>
                    <label>Confirm Password</label>
                </div>

                <div>
                    <select name="role" required>
                        <option value="">--Select Role--</option>
                        <option value="customer">Customer</option>
                        <option value="companies">Companies</option>
                    </select>
                </div>

                <div class="terms-conditions">
    <label>
        <input type="checkbox" name="terms" id="termsCheckbox"> I agree to 
        <a href="#" id="openTerms">terms & conditions</a>
    </label>
</div>

                <button type="submit" class="btn" value="signup" name="submit">Sign Up</button>
                <div class="login-register">
                    <p>Already have an account? 
                        <a href="index.php" class="login-link">Sign In</a></p>
                </div>
            </div>
        </form>
    </div>
</div>

<div id="termsModal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Terms and Conditions</h2>
    <div class="terms-content">
      <h3>Welcome to RoomGenius!</h3>
      <p>These terms and conditions outline the rules and regulations for the use of RoomGenius's Website.</p>
      
      <h4>1. Acceptance of Terms</h4>
      <p>By accessing this website, you accept these terms and conditions in full. If you disagree with these terms and conditions or any part of them, you must not use this website.</p>
      
      <h4>2. User Accounts</h4>
      <p>When you create an account with us, you guarantee that the information you provide is accurate, complete, and current at all times. Inaccurate, incomplete, or obsolete information may result in the immediate termination of your account on the Service.</p>
      
      <h4>3. Privacy Policy</h4>
      <p>Your use of our service is also governed by our Privacy Policy, which is incorporated by reference into these Terms and Conditions.</p>
      
      <h4>4. Intellectual Property</h4>
      <p>The Service and its original content, features, and functionality are and will remain the exclusive property of RoomGenius. The Service is protected by copyright, trademark, and other laws.</p>
      
      <h4>5. Termination</h4>
      <p>We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever, including but not limited to a breach of the Terms.</p>
    </div>
    <button id="acceptTerms" class="btn">I Accept</button>
  </div>
</div>



</body>

<script>
function checkPasswordStrength(password) {
    const strengthText = document.getElementById('password-strength');
    let strength = 0;

    if (password.length >= 8) strength++;
    if (/[A-Z]/.test(password)) strength++;
    if (/[0-9]/.test(password)) strength++;
    if (/[\W]/.test(password)) strength++;

    if (strength === 0) {
        strengthText.textContent = '';
        strengthText.style.color = '';
    } else if (strength <= 2) {
        strengthText.textContent = 'Weak';
        strengthText.style.color = 'red';
    } else if (strength === 3) {
        strengthText.textContent = 'Medium';
        strengthText.style.color = 'orange';
    } else {
        strengthText.textContent = 'Strong';
        strengthText.style.color = 'green';
    }
}



// Get the modal
const modal = document.getElementById("termsModal");

// Get the button that opens the modal
const termsLink = document.getElementById("openTerms");

// Get the <span> element that closes the modal
const closeBtn = document.getElementsByClassName("close")[0];

// Get the accept button
const acceptBtn = document.getElementById("acceptTerms");

// Get the checkbox
const termsCheckbox = document.getElementById("termsCheckbox");

// When the user clicks on the terms link, open the modal
termsLink.onclick = function(e) {
    e.preventDefault();
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
closeBtn.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks on accept button
acceptBtn.onclick = function() {
    termsCheckbox.checked = true;
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>