<?php
session_start();
// Include the database connection file
include('db.php');

// Check if the form is submitted
if (isset($_POST['submit'])) {
    // Get form data
    $name = $_POST['name'];
    $email = $_POST['email'];
    $password = $_POST['password'];
    $confirmPassword = $_POST['confirmPassword'];
    $role = $_POST['role'];

    // Validate if passwords match
    if ($password === $confirmPassword) {
        // Hash the password before storing
        $hashedPassword = password_hash($password, PASSWORD_DEFAULT);

        // Validate email uniqueness
        $stmt = $conn->prepare("SELECT id FROM users WHERE email = ?");
        $stmt->bind_param("s", $email);
        $stmt->execute();
        $stmt->store_result();

        if ($stmt->num_rows > 0) {
            $error_message = "Email already registered!";
        } else {
            // Check if terms are accepted
            if (!isset($_POST['terms'])) {
                $error_message = "You must agree to the terms and conditions!";
            } else {
                $created_at = $updated_at = date("Y-m-d H:i:s");

                // Insert into users table
                $insert_stmt = $conn->prepare("INSERT INTO users (name, email, password, role, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)");
                $insert_stmt->bind_param("ssssss", $name, $email, $hashedPassword, $role, $created_at, $updated_at);

                if ($insert_stmt->execute()) {
                    $user_id = $insert_stmt->insert_id;

                    // After inserting the company into the database
if ($role === 'companies') {
    $company_name = $name . "'s Company";
    $insert_company = $conn->prepare("INSERT INTO companies (user_id, company_name, company_email, company_address, company_phone, company_website) VALUES (?, ?, ?, '', '', '')");
    $insert_company->bind_param("iss", $user_id, $company_name, $email);
    $insert_company->execute();
    
    // Get the company ID (auto-generated by the database)
    $company_id = $insert_company->insert_id;

    // Set the session variables for company
    $_SESSION['company_id'] = $company_id; // Store the company ID in the session
    
    $insert_company->close();
}

// Redirect based on user role
if ($role === 'companies') {
    header('Location: companies.php');  // Redirect to companies page
} else {
    header('Location: gallery.php');  // Redirect to gallery page for customers
}
exit();


                } else {
                    $error_message = "Error while inserting user!";
                }

                $insert_stmt->close();
            }
        }

        $stmt->close();
    } else {
        $error_message = "Passwords do not match!";
    }
}
?>

<!-- HTML Form -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="signup.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/remixicon/fonts/remixicon.css">
    <title>Sign Up</title>
</head>
<body>

<div class="nav">
    <h2 class="logo">
        <i class="fas fa-brain"></i>
        <i class="fas fa-couch"></i>
        RoomGenius
    </h2>
</div>

<div class="background">
    <div class="wrapper">
        <form action="signup.php" method="post">
            <h2>Sign Up</h2>
            <?php
            if (isset($error_message)) {
                echo '<p style="color:red; text-align:center;">' . $error_message . '</p>';
            }
            ?>
            <div class="input-field">
                <div class="input-box">
                    <span class="icon"><i class='bx bxs-user'></i></span>
                    <input type="text" name="name" required>
                    <label>Name</label>
                </div>
                <div class="input-box">
                    <span class="icon"><i class="ri-mail-line"></i></span>
                    <input type="email" name="email" required>
                    <label>Email</label>
                </div>

                <div class="input-box">
                    <span class="icon"><i class='bx bxs-lock-alt'></i></span>
                    <input type="password" id="password" name="password" required oninput="checkPasswordStrength(this.value)">
                    <label>Password</label>
                    <div id="password-strength" class="strength-text"></div>
                </div>

                <div class="input-box">
                    <span class="icon"><i class='bx bxs-lock-alt'></i></span>
                    <input type="password" name="confirmPassword" required>
                    <label>Confirm Password</label>
                </div>

                <div>
                    <select name="role" required>
                        <option value="">--Select Role--</option>
                        <option value="customer">Customer</option>
                        <option value="companies">Companies</option>
                    </select>
                </div>

                <div class="terms-conditions">
                    <label><input type="checkbox" name="terms"> I agree to terms & conditions</label>
                </div>

                <button type="submit" class="btn" value="signup" name="submit">Sign Up</button>
                <div class="login-register">
                    <p>Already have an account? 
                        <a href="index.php" class="login-link">Sign In</a></p>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
function checkPasswordStrength(password) {
    const strengthText = document.getElementById('password-strength');
    let strength = 0;

    if (password.length >= 8) strength++;
    if (/[A-Z]/.test(password)) strength++;
    if (/[0-9]/.test(password)) strength++;
    if (/[\W]/.test(password)) strength++;

    if (strength === 0) {
        strengthText.textContent = '';
        strengthText.style.color = '';
    } else if (strength <= 2) {
        strengthText.textContent = 'Weak';
        strengthText.style.color = 'red';
    } else if (strength === 3) {
        strengthText.textContent = 'Medium';
        strengthText.style.color = 'orange';
    } else {
        strengthText.textContent = 'Strong';
        strengthText.style.color = 'green';
    }
}
</script>

</body>
</html>
